# Generated by Django 5.0.2 on 2024-04-09 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0002_icon_remove_project_page_project_title_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="image",
            field=models.ImageField(upload_to="static/"),
        ),
    ]
