# Generated by Django 5.0.4 on 2024-04-09 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Icon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image_url', models.URLField()),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='page',
        ),
        migrations.AddField(
            model_name='project',
            name='title',
            field=models.CharField(default='Untitled', max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(upload_to='project_images/'),
        ),
        migrations.AddField(
            model_name='project',
            name='icons',
            field=models.ManyToManyField(to='project.icon'),
        ),
        migrations.DeleteModel(
            name='Page',
        ),
    ]
